#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/readtheorg.css" />
#+TITLE: 八代思域的优点与缺点
#+AUTHOR: zhcosin
#+DATE: 2019-07-18
#+OPTIONS:   ^:{} \n:t 
#+LANGUAGE: zh-CN

本文说一下我这车的优点与缺点。

* 优点
  

** 小毛病少
本田的品控确实做的不错，除了为数不多的几个已知通病(机脚垫容易坏，转向助力泵渗漏，离合踏板异响，车窗升降开关容易坏)以外，十多年下来基本不会出什么毛病。 本田的自然吸气发动机非常稳定，除了换机油机滤和火花塞之外，什么都不用操心，而且积碳也少。手动挡变速箱因为结构简单，省心耐用.换变速箱油只需要直接放掉再加就行，而且只要两升，也没有滤芯啥的，保养是真心便宜。

** 保养便宜
本田的车，基本都有这个优点，用的正时链条，终生免维护，一条发动机附件驱动皮带用到20万公里没任何问题。这车没有自动启停，所以换电瓶也贼便宜，两三百块钱。

** 动力不错
140马力对于一台A级车来说，虽然不如涡轮发动机那么猛，但是也足够你激情一把了，配合上手动档变速器，二档破百可不是说说而已。加上又是自吸发动机，动力线性不突兀。

** 操控不错
这个液压助力的转向手感非常好，略沉，路感清晰。减震偏硬，坐姿低，车身过弯和变道比较灵活。

** 内饰
双层液晶仪表台非常漂亮，电子数字的时速显示，比现在30万以内的绝大多数车的仪表都漂亮。后排地板中间纯平无凸起，坐三个人的时候中间的人不会很难受，这个很难得。

** 全尺寸备胎啊
简直良心，连轮毂跟车上的其它四个都是一模一样，换上就可以一直用不必再换回来。

* 缺点

** 隔音差
时速达到70以上噪音明显，跑高速时车内说话需要大声说。

** 油耗略高
与现在的十代思域相比要高一截，市区基本九个左右，高速六个。

** A柱盲区大
两个小三角窗完全可以挡住一个骑电瓶车的，转弯时要注意偏头观察，尤其是左转。

** 通病
祖传助力泵渗漏，机脚垫容易坏，方向机也容易渗漏，离合踏板异响，原地打方向异响，玻璃升降开关易坏，不过解决起来都要不了几个钱。

