#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/readtheorg.css" />
#+TITLE: 数学书目清单与简介
#+AUTHOR: zhcosin
#+OPTIONS:   ^:{} \n:t 
#+LANGUAGE: zh-CN

这里是一份数学参考书列表，列出了我参考过的和打算以后参考的数学书目。
   
* 初等数学

     1. 《不等式的秘密》
     作者: [越南]范建熊，隋振林(译)
     出版社: 哈尔滨工业大学出版社
     简介: 竞赛不等式的集大成者，对于不参加数学竞赛的人来说比较难。如果你对不等式有浓厚兴趣，则此书必读。

     1. 《几何瑰宝》
     作者: 沈文选，杨清桃.
     出版社: 哈尔滨工业大学出版社
     简介: 百科全书似的初等几何，内容涵盖了欧氏几何的大部分内容，内容有浅有深，重在全面。

     1. 《圆锥曲线论》
     作者: [古希腊]阿波罗尼奥斯
     出版社: 陕西科学技术出版社
     简介: 古典欧氏几何的最高峰，作者在两千多年前的古希腊，用欧氏几何的方法将圆锥曲线的性质几乎一网打尽，以致于后人在长达两千余年间没能在这个领域有多少新的发现，直到笛卡尔坐标几何的诞生。
     
     1. [[http://kuing.orzweb.net/viewthread.php?tid%3D3757&extra%3Dpage%253D1][《kuing 网络撸题集》]] 
     作者: kuing 
     出版社: 网络电子书
     简介: 网络上的数学高手 kuing 的大作，是一份难题集，篇幅较大，不等式部分较难。

* 数论

     1. 《初等数论》 
     作者: 闵嗣鹤,严士健
     出版社: 高等教育出版社
     简介: 此书篇幅不大，适合初等数论入门，也适合参加竞赛的学生阅读.

     1. 《数论导引》
     作者: 华罗庚
     出版社: 高等教育出版社
     简介: 大师手笔，篇幅较多，内容全面，比较深，就算你不从头到尾读，也应该拿它作参考书读。

     1. 《初等数论》 
     作者: 潘承洞,潘承彪
     出版社: 高等教育出版社.
     简介: 
       
* 代数
  
** 高等代数
  
     1. 《高等代数》 
     作者: 北京大学几何与代数教研室前代数小组
     出版社: 高等教育出版社
     简介: 行文处处体现着数学大师的风范，书中的证明非常吸引人。
       
** 抽象代数
       
     1. 《代数学引论》
     作者: [前苏联]柯斯特利金
     出版社: 高等教育出版社
     简介: 篇幅较大(三卷本).

     1. 《代数学引论》
     作者: 聂灵沼,丁石孙
     出版社: 高等教育出版社
     简介: 出自北京大学的数学大师之手.

     1. 《从一元一次方程到伽罗瓦理论》
     作者: 冯承天
     出版社: 华东师范大学出版社
     简介: 这是一部科普性质的书，只介绍概念和结论并加以解释，证明很少。
      
* 分析
  
     1. 《高等数学引论》 
     作者: 华罗庚
     出版社: 高等教育出版社
     简介: 华罗庚的手笔，分四册，前两册是微积分，第三册是线性代数，第四册是复变函数，该书侧重把高等数学拉通起来讲，而不是分好几门课.

** 微积分

     1. 《微积分学教程》
     作者: [前苏联]菲赫金哥尔茨
     出版社: 高等教育出版社
     简介: 该书是苏联数学地位的代表之作，是用传统手法（指不引入实变和泛函的观点）研究微积分的最高成果，篇幅巨大(三卷本)，内容之全面丰富无出其右，在严格性和通俗易读之间把握了一个非常好的平衡，对于需要认真学习微积分的人来说，该书是圣经。

     1. 《微积分与数学分析引论》
     作者: [美]F.约翰, R.柯朗
     出版社: 科学出版社
     简介:

     1. 《数学分析习题集》 
     作者: [前苏联]吉米诺维奇
     出版社: 高等教育出版社
     简介: 驰名世界的一份微积分习题集。
       
** 实变函数

** 复分析

** 泛函分析

** 微分方程
 
