#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/readtheorg.css" />
#+TITLE: free-math: zhcosin's Home
#+AUTHOR: zhcosin
#+OPTIONS:   ^:{} \n:t 
#+LANGUAGE: zh-CN


  欢迎光临 zhcosin 的个人主页，一句话概括我: 数学爱好者，程序员，喜欢古典文学/历史，以及一个普通的爸爸。

  我的 =GitHub= 主页: [[https://github.com/zhcosin]]
  我的 =coding.net= 主页: [[https://coding.net/u/zhcosin/project]]
  如果有问题需要联系我，可以发 E-mail: zhcosin@163.com
  

* 数学
     
     数学始终是我的第一兴趣，目前致力于学习高等数学，并且预计将持续几年时间。
     
** 初等数学
     
     在初等数学领域，我写了一份笔记，即 [[https://coding.net/u/zhcosin/p/math-notes-publish/git/blob/master/elementary-math-note.pdf][《初等数学笔记》]] ，用 LaTeX 排版的，内容包括初等数论、函数与方程、不等式、欧氏几何、解析几何、组合等内容，目前大致成形，但还有许多需要补充的内容和需要完善的地方，预计全部完成后篇幅应接近300页。暂时只提供 =PDF= 下载，以后可能会提供 =HTML= 在线阅读。
     
** 高等数学
     
     我更大的兴趣在于高等数学，这主要有分析和代数两个方向，分析方向的主要内容是微积分、实变与泛函、复分析、微分方程，代数方向主要是高等代数和抽象代数，这些课程已经足够我花费几年的时间来学习了，我正在制作一份 [[file:math/books-list.org][数学书目清单]] (不限于高等数学)，列出了主要的参考书以及简短介绍。还有学习这些课程所做的笔记: [[https://coding.net/u/zhcosin/p/math-notes-publish/git/blob/master/calculus-note.pdf][微积分学笔记]] . 
     
** 数学资源
     
     这里罗列了一些有用的数学资料网址，包括论坛、电子书等资源。

* 计算机工具与软件
  
** debian 操作系统
   
   一个自由的 =linux= 操作系统的发行版，旨在“自由软件”，具备出色的稳定性，是个常年不需要重启的服务器操作系统。我正致力于打造基于 =debian= 的稳定工作环境，下面是一些相关链接:
   - [[https://www.debian.org/][debian 官网]]
   - [[https://www.debian.org/doc/manuals/debian-reference/index.zh-cn.html][debian 参考手册]]
   - [[https://www.debiancn.org/][debian 中文社区]]
   - [[http://www.ctex.org/documents/shredder/linux.html][完全用 GNU/Linux 工作]]
     
** vim 与 Emacs

   一个是编辑器之神，一个是神之编辑器，作为两大黑客级别的编辑器，弥漫于两者忠实粉丝之间的“圣战”战火波及到了互联网上所有与编辑器有关的页面。 =Vim= 的模式编辑方式非常高效，但它的扩展语言 =VimScript= 不如 =Emacs Lisp= 强大，因为后者从属于 =Lisp= 语言族，是一门语法简单但表现力强大的语言， =Emacs= 本质上就是一个编程平台。得益于 =Emacs= 的可扩展性，我使用 =evil= 在 =Emacs= 中来模拟 =Vim= 的编辑方式，这使得工作效率相当高。
   
   另外 =Emacs= 自带的 =org-mode= 模式是一个比 =markdown= 功能更加丰富的文档写作工具，并且得益于 =Emacs Lisp= ，具备高度可定制性，是写作笔记的利器，我用它写作日常文档，包括本页面也是用 =org-mode= 生成的。
   - [[http://www.vim.org/][vim 官网]]
   - [[https://www.gnu.org/software/emacs/][Emacs 官网]]
   - [[http://www.cnblogs.com/babe/archive/2012/04/11/2441620.html][钗黛双收：若你也同Vim难割舍，却又看Emacs情切切]]
   - [[https://emacs-china.org/][Emacs 中文社区]]
   - [[http://book.emacs-china.org/][21 天掌握 Emacs]]
   - [[http://www.fuzihao.org/blog/2015/02/19/org-mode%25E6%2595%2599%25E7%25A8%258B/][org-mode 入门教程]]     

** Git

   =Git= 是一个分布式版本管理软件，由 =linux= 之父 =Linus Torvalds= 亲手设计和实现，而围绕它的 =GitHub= 网站已经成为全世界的开源项目的集散地，国内也有 =coding.net= 这样的优秀的 =Git= 代码托管平台。我用 =Git= 维护我的所有重要的文档，包括数学笔记、博客文章、软件以及系统的重要配置文件，包括本页面也被纳入 =Git= 的管理之下。
   - [[https://git-scm.com/][Git 官网]]
   - [[http://iissnan.com/progit/][Pro Git 简体中文版]]
   - [[https://github.com/][GitHub]]
   - [[https://coding.net/][Coding.net 代码托管网站]]
     
   
** LaTeX 
      
      =LaTeX= 是一个专业的科技论文、图书排版系统，其排版的数学公式尤其精美，是当今科技排版的标准，我的数学笔记都是用它排版的。下面是一些相关的链接:
      - [[https://www.latex-project.org/][LaTeX 官网]]
      - [[http://mirrors.ustc.edu.cn/CTAN/info/lshort/chinese/lshort-zh-cn.pdf][一份不太简短的 LaTeX2e介绍]]
      - [[http://www.ctex.org/documents/shredder/tex_frame.html][TeX - 漂亮而且有趣]]
      - [[http://www.latexstudio.net/][LaTeX 工作室]]
   
** TeXmacs
    
      一个所见即所得的排版系统，可视化的操作方式，却能得到与 =LaTeX= 类似的效果，但软件目前不太成熟，我用它来打草稿和写作讨论稿。
      - [[http://www.texmacs.org/tmweb/home/welcome.en.html][TeXmacs 官网]]
      - [[http://www.yinwang.org/blog-cn/2012/09/18/texmacs][一个真正所见即所得的排版系统]]
      - [[http://x-wei.github.io/TeXmacs_intro.html][学术文章写作利器 - TeXmacs 介绍]]
      - [[https://github.com/zhcosin/introduction-docs/blob/master/introduction-texmacs/introduction-texmacs.org][使用 TeXmacs 写作数学文档]]

** Maxima

      一个计算机代数系统，类似于 =Mathematica=.
     
** rime 输入法框架

   作为中国人计算机上的最基础的一个软件，选择性很大，用的最多的是搜狗输入法，但自从发现搜狗偷偷在我的手机中安装各种各样的垃圾软件（如搜狗市场）时，我愤怒了，于是开始寻求输入法领域中的自由软件，终于，我找到了 =rime= 输入法框架，由一个 =Lisp= 狂人所开发，通过不同的配置能实现不同的输入法，而且顺便解决了我之前一直头疼的 =linux= 下的五笔都是98版本而不是我熟悉的86版本的问题，于是现在我的计算机中只有 =rime= 输入法了。推荐跟我一样寻求干净可定制的输入法的朋友使用它。

    - [[http://rime.im/][RIME 中州韵输入引擎]]

* 历史/古典文学
  我喜欢历史和古典文学，以下是一些计划要读的书单。
   - 史记
   - 三国志
   - 资治通鉴
   - 红楼梦
   - 三国演义
   - 东周列国志
